parameters:
#    apte_instagram.example.class: Apte\InstagramBundle\Example

services:
#    apte_instagram.example:
#        class: %apte_instagram.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
